void calculate_all_source_terms(const reconstructed_prims_struct *restrict reconstructed_prims, const metric_quantities_struct *restrict metric_quantities, const metric_quantities_derivatives_struct *restrict metric_quantities_derivatives, conservative_sources_struct *restrict conservative_sources);
void calculate_characteristic_speed_0th_direction(const reconstructed_prims_struct *restrict reconstructed_prims_r, const reconstructed_prims_struct *restrict reconstructed_prims_l,const metric_face_quantities_struct *restrict metric_face_quantities, conservative_fluxes_struct *restrict conservative_fluxes);
void calculate_characteristic_speed_1th_direction(const reconstructed_prims_struct *restrict reconstructed_prims_r, const reconstructed_prims_struct *restrict reconstructed_prims_l,const metric_face_quantities_struct *restrict metric_face_quantities, conservative_fluxes_struct *restrict conservative_fluxes);
void calculate_characteristic_speed_2th_direction(const reconstructed_prims_struct *restrict reconstructed_prims_r, const reconstructed_prims_struct *restrict reconstructed_prims_l,const metric_face_quantities_struct *restrict metric_face_quantities, conservative_fluxes_struct *restrict conservative_fluxes);
void calculate_HLLE_fluxes0(const reconstructed_prims_struct *restrict reconstructed_prims_r, const reconstructed_prims_struct *restrict reconstructed_prims_l,const metric_face_quantities_struct *restrict metric_face_quantities, conservative_fluxes_struct *restrict conservative_fluxes);
void calculate_HLLE_fluxes1(const reconstructed_prims_struct *restrict reconstructed_prims_r, const reconstructed_prims_struct *restrict reconstructed_prims_l,const metric_face_quantities_struct *restrict metric_face_quantities, conservative_fluxes_struct *restrict conservative_fluxes);
void calculate_HLLE_fluxes2(const reconstructed_prims_struct *restrict reconstructed_prims_r, const reconstructed_prims_struct *restrict reconstructed_prims_l,const metric_face_quantities_struct *restrict metric_face_quantities, conservative_fluxes_struct *restrict conservative_fluxes);
void initialize_structs(const int ijk, const paramstruct *params, const double *restrict auxevol_gfs, reconstructed_prims_struct *restrict reconstructed_prims, reconstructed_prims_struct *restrict reconstructed_prims_r, reconstructed_prims_struct *restrict reconstructed_prims_l, metric_quantities_struct *restrict metric_quantities, metric_face_quantities_struct *restrict metric_face_quantities, metric_quantities_derivatives_struct *restrict metric_quantities_derivatives);
REAL find_timestep(const paramstruct *restrict params, REAL *restrict xx[3], const REAL CFL_FACTOR);
void xx_to_Cart(const paramstruct *restrict params, REAL *restrict xx[3],const int i0,const int i1,const int i2, REAL xCart[3]);
void set_Nxx_dxx_invdx_params__and__xx(const int EigenCoord, const int Nxx[3],paramstruct *restrict params, REAL *restrict xx[3]);
void Cart_to_xx_and_nearest_i0i1i2(const paramstruct *restrict params, const REAL xCart[3], REAL xx[3], int Cart_to_i0i1i2[3]);
void Cart_to_xx_and_nearest_i0i1i2_global_grid_center(const paramstruct *restrict params, const REAL xCart[3], REAL xx[3], int Cart_to_i0i1i2[3]);
void set_Cparameters_to_default(paramstruct *restrict params);
void reconstruct_set_of_prims_PPM(const paramstruct *restrict params, const cGH *cctkGH,const int *cctk_lsh,const int flux_dirn,const int num_prims_to_reconstruct,const int *which_prims_to_reconstruct,eos_struct *restrict eos,
                                         gf_and_gz_struct *in_prims,gf_and_gz_struct *out_prims_r,gf_and_gz_struct *out_prims_l,CCTK_REAL *ftilde_gf, CCTK_REAL *temporary);

